apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    storage: shared
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs
    server: 192.168.15.3
  storageClassName: giropops