apiVersion: v1
kind: Namespace
metadata:
  name: treinamento-ch2

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-comportado
  namespace: treinamento-ch2
spec:
  containers:
    - name: memory-eater
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
      resources:
        requests:
          memory: "250Mi"
        limits:
          memory: "300Mi"