apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { }
    http {
        server {
            listen 80;
            listen 443 ssl;
            ssl_certificate /etc/nginx/ssl/nginx.crt;
            ssl_certificate_key /etc/nginx/ssl/nginx.key;

            location / {
                return 200 'Hello, Secure World!\n';
                add_header Content-Type text/plain;
            }
        }
    }